cache:
  mount:
    - node_modules
build:
  image: node:wheezy
  commands:
    - npm install --unsafe-perm
    - npm run lint
    # - npm test

# Example deploy, check readme and github.com/jordond/docker-basesite for more info
deploy:
  ssh:
    host: hoogit.ca
    user: drone
    commands:
      - docker-restart ratemd
    when:
      branch: master
